### ISSUE TITLE
Impossible to make submissions

### ISSUE THREAD

**Issue by Mehliug-git** [CIRCL/PyEUPI#3]
Hi !

Why I have a "401 Unauthorized" error when I want submit a URL ? 
I don't have the right to do this ? If so, how can I get them ?

Thanks

**Comment by Rafiot** [comment]
Hi! yes, you need to get in touch with the EUPI folks and get an API key.

**Comment by Mehliug-git** [comment]
Okay, because I have a API key, but no right 

I send us a mail thx !

**Comment by Mehliug-git** [comment]
Closed
